import type { AbilityDef } from "./types";

/**
 * Every avatar in the roster wields exactly one UNIQUE ability — 35 avatars,
 * 35 distinct mechanics (no two share a `kind`). Keyed by avatar id so a
 * player's ability is whatever character they picked. The engine is
 * data-driven: same machinery, per-avatar flavor + parameters.
 */
export const ABILITIES: Record<string, AbilityDef> = {
  modi: {
    id: "modi", avatarId: "modi", name: "Modi", abilityName: "Modi-fied Points",
    tagline: "Bank the same points as whoever answers correctly.",
    longDesc: "On the next question, whoever answers correctly wins the points — and Modi banks the exact same amount too, whether Modi buzzed or not. Double the winners, one answer.",
    kind: "modiShare", animation: "glitch",
    emoji: "🪔", accent: "warning",
  },
  selmon: {
    id: "selmon", avatarId: "selmon", name: "Selmon Bhoi", abilityName: "Selmon Tax",
    tagline: "Everyone else loses 15% — you keep the haul.",
    longDesc: "A mass 'contribution': every other player instantly loses 15% of their score (rounded), and you gain the entire sum. The host applies the Bhoi tax at once.",
    kind: "taxNow", animation: "chaos", immediate: true, params: { confirm: true },
    emoji: "🐅", accent: "primary",
  },
  daredevil: {
    id: "daredevil", avatarId: "daredevil", name: "Daredevil", abilityName: "Blind Skeleton",
    tagline: "See the next answer's letter skeleton.",
    longDesc: "On the next question, YOU see a letter skeleton of the correct answer — the first and last letters of every word — for the whole question. Star-spangled fingers crossed on the rest.",
    kind: "clueSkeleton", animation: "flash", params: { clueType: "skeletonAnswer" },
    emoji: "🦸", accent: "danger",
  },
  kratos: {
    id: "kratos", avatarId: "kratos", name: "Kratos", abilityName: "God of Ward",
    tagline: "Steal 25% from a chosen player.",
    longDesc: "Choose a player and instantly pocket 25% of their current score. Rage unleashed, boy.",
    kind: "stealNow", animation: "impact", needsTarget: true, immediate: true, params: { pct: 0.25, confirm: true },
    emoji: "🪓", accent: "danger",
  },
  thanos: {
    id: "thanos", avatarId: "thanos", name: "Thanos", abilityName: "Perfectly Balanced",
    tagline: "Halve another player's score.",
    longDesc: "Choose a player — their score is instantly reduced to half. As all things should be.",
    kind: "halveNow", animation: "impact", needsTarget: true, immediate: true, params: { confirm: true },
    emoji: "💜", accent: "ink",
  },
  dead: {
    id: "dead", avatarId: "dead", name: "Deadpool", abilityName: "You Can't Kill Me",
    tagline: "Your next wrong answer doesn't count.",
    longDesc: "Your next wrong answer is forgiven: no score loss, your buzz stays in the queue, and if you then answer the same question correctly you still bank half the value.",
    kind: "secondChance", animation: "zoom",
    emoji: "🔴", accent: "danger",
  },
  joker: {
    id: "joker", avatarId: "joker", name: "Joker", abilityName: "Why So Serious?",
    tagline: "Roll your next correct ×1.5, ×2 or ×2.5.",
    longDesc: "A lucky roll locked in the moment you activate: your next correct answer is worth ×1.5, ×2… or a jackpot ×2.5. No negatives — the house always pays.",
    kind: "rollNow", animation: "chaos", params: { roll: true, confirm: true },
    emoji: "🃏", accent: "secondary",
  },
  doom: {
    id: "doom", avatarId: "doom", name: "Dr. Doom", abilityName: "Foresight",
    tagline: "See the first 3 letters of the next answer.",
    longDesc: "On the next question you can see the first 3 letters of the correct answer — while everyone else sweat bullets.",
    kind: "clue3", animation: "freeze", params: { clueType: "letters3" },
    emoji: "🤖", accent: "success",
  },
  homelander: {
    id: "homelander", avatarId: "homelander", name: "Homelander", abilityName: "I Can Do Whatever I Want",
    tagline: "Take 90% of the highest scorer.",
    longDesc: "Instantly strip 90% of the current highest scorer's bank and pocket it. Approved (by you).",
    kind: "grabHighest", animation: "impact", autoTarget: true, immediate: true, params: { targetMode: "leader", pct: 0.9, confirm: true },
    emoji: "🌟", accent: "primary",
  },
  honey: {
    id: "honey", avatarId: "honey", name: "Honey Singh", abilityName: "Desi Half-Loss",
    tagline: "Your next wrong answer costs only half.",
    longDesc: "Honey-sweetened: the next time you answer wrong, you lose only half the value instead of the full amount.",
    kind: "halfWrong", animation: "burst",
    emoji: "🍯", accent: "warning",
  },
  hritik: {
    id: "hritik", avatarId: "hritik", name: "Hrithik", abilityName: "Jadoo ×2",
    tagline: "Double your score instantly.",
    longDesc: "Jadoo magic: your current score is doubled on the spot. Pure power, no strings.",
    kind: "doubleNow", animation: "glitch", immediate: true, params: { confirm: true },
    emoji: "💥", accent: "primary",
  },
  iron: {
    id: "iron", avatarId: "iron", name: "Iron Man", abilityName: "JARVIS Hints",
    tagline: "See 2 letters + the length of the next answer.",
    longDesc: "On the next question, JARVIS shows you two random letters of the answer and its total length.",
    kind: "clue2", animation: "spotlight", params: { clueType: "letters2" },
    emoji: "🦾", accent: "danger",
  },
  john: {
    id: "john", avatarId: "john", name: "John Cena", abilityName: "You Can't See Me",
    tagline: "Draft a player: they gain 0 points next question.",
    longDesc: "Choose a player — even if they answer the next question correctly, they bank ZERO points for it. Bait set.",
    kind: "draft", animation: "flash", needsTarget: true, params: { confirm: true },
    emoji: "👀", accent: "warning",
  },
  anime: {
    id: "anime", avatarId: "anime", name: "Anime Freak", abilityName: "Waifu Swap",
    tagline: "Swap your score with a chosen player.",
    longDesc: "Trade scores with any player — their total becomes yours and yours becomes theirs. The ULTIMATE glitch.",
    kind: "swapNow", animation: "glitch", needsTarget: true, immediate: true, params: { confirm: true },
    emoji: "🎌", accent: "secondary",
  },
  billy: {
    id: "billy", avatarId: "billy", name: "Billy Butcher", abilityName: "Line-Jump",
    tagline: "Your next buzz jumps to #1.",
    longDesc: "No matter how fast anyone else slams their button, your next buzz is ranked FIRST. Cheeky, inneit.",
    kind: "frontOfLine", animation: "zoom",
    emoji: "🔪", accent: "danger",
  },
  chims: {
    id: "chims", avatarId: "chims", name: "Chimps", abilityName: "Sussy Length",
    tagline: "See the length of the next answer.",
    longDesc: "On the next question you learn exactly how long the answer is — suspiciously helpful.",
    kind: "clueVague", animation: "freeze", params: { clueType: "vague" },
    emoji: "🐵", accent: "success",
  },
  hamza: {
    id: "hamza", avatarId: "hamza", name: "Hamza", abilityName: "Jinxed",
    tagline: "A player's next correct is worth half.",
    longDesc: "Choose a player — their next correct answer is only worth half the value. A pinch of Hamza-bad-luck.",
    kind: "jinx", animation: "burst", needsTarget: true, params: { confirm: true },
    emoji: "🍀", accent: "success",
  },
  luffy: {
    id: "luffy", avatarId: "luffy", name: "Luffy", abilityName: "Meat Refuel",
    tagline: "Your next correct answer earns +150 extra.",
    longDesc: "Refuel like Luffy after a plate of meat: your next correct answer adds a flat +150 on top of whatever it's worth.",
    kind: "refuel", animation: "zoom",
    emoji: "🍖", accent: "success",
  },
  monkey: {
    id: "monkey", avatarId: "monkey", name: "Monkey", abilityName: "Banana First-Last",
    tagline: "See the first & last letters of the next answer.",
    longDesc: "On the next question you see the first and last letters of the correct answer.",
    kind: "clueFirstLast", animation: "burst", params: { clueType: "firstLast" },
    emoji: "🍌", accent: "warning",
  },
  msd: {
    id: "msd", avatarId: "msd", name: "Thala", abilityName: "Captain's ×7",
    tagline: "Multiply your score by 7.",
    longDesc: "Captain authority: your current score is instantly multiplied by 7. A proper Thala power-up.",
    kind: "multiplyNow", animation: "glitch", immediate: true, params: { mult: 7, confirm: true },
    emoji: "👑", accent: "primary",
  },
  perry: {
    id: "perry", avatarId: "perry", name: "Perry", abilityName: "Ghost Protocol",
    tagline: "Vanish from the leaderboard for a question.",
    longDesc: "While the next question is live, other players can't see you on standings or in the buzz queue. Spooky.",
    kind: "hide", animation: "freeze",
    emoji: "🥷", accent: "ink",
  },
  prabhas: {
    id: "prabhas", avatarId: "prabhas", name: "Prabhas", abilityName: "Rebel Confiscation",
    tagline: "Everyone else loses 10%.",
    longDesc: "A mass penalty: every other player instantly loses 10% of their score. Rebel energy takes something from everyone.",
    kind: "confiscate", animation: "impact", immediate: true, params: { confirm: true },
    emoji: "🔥", accent: "danger",
  },
  professor: {
    id: "professor", avatarId: "professor", name: "Professor", abilityName: "Academic Insight",
    tagline: "See length + vowels of the next answer.",
    longDesc: "On the next question you learn the answer's length and how many vowels it contains.",
    kind: "clueLength", animation: "spotlight", params: { clueType: "length" },
    emoji: "🧠", accent: "ink",
  },
  pw: {
    id: "pw", avatarId: "pw", name: "PW", abilityName: "Price Hike",
    tagline: "Next question: everyone's correct is worth ×1.5.",
    longDesc: "Like a price hike at the end of the year: on the next question, EVERYONE who answers correctly earns 1.5× — a rising tide lifts all boats.",
    kind: "hike", animation: "glitch",
    emoji: "📈", accent: "primary",
  },
  raftaar: {
    id: "raftaar", avatarId: "raftaar", name: "Raftaar", abilityName: "Echo Bars",
    tagline: "Your next correct earns +40% of the value.",
    longDesc: "On your next correct answer you bank the value PLUS 40% of it — a double-time bonus on top.",
    kind: "echo", animation: "glitch",
    emoji: "🎤", accent: "secondary",
  },
  ryder: {
    id: "ryder", avatarId: "ryder", name: "Ryder", abilityName: "Prime Time",
    tagline: "Instantly gain +250.",
    longDesc: "Prime you: instantly add 250 points to your score. No strings attached.",
    kind: "prime", animation: "zoom", immediate: true, params: { confirm: true },
    emoji: "🛒", accent: "warning",
  },
  samay: {
    id: "samay", avatarId: "samay", name: "Samay Raina", abilityName: "Dark Jokes = Jail",
    tagline: "Wrong answerers go to jail.",
    longDesc: "Activate this before a question. Anyone who buzzes and answers wrong on that question is jailed — they can't buzz on the next one. The roast writes itself.",
    kind: "jailWrong", animation: "chaos",
    emoji: "🔒", accent: "danger",
  },
  srk: {
    id: "srk", avatarId: "srk", name: "King Khan", abilityName: "Pathaan Shield",
    tagline: "Your next wrong is ignored — but you lose the turn.",
    longDesc: "Your next wrong answer costs nothing (no score loss), but unlike a bounce-back you DON'T keep your buzz — the turn passes on. Solid defence.",
    kind: "shield", animation: "impact",
    emoji: "🕶️", accent: "primary",
  },
  tate: {
    id: "tate", avatarId: "tate", name: "Tate", abilityName: "Ligma Trap",
    tagline: "Trap a player: their next wrong costs double.",
    longDesc: "Choose a player. If their next answer is wrong, they lose DOUBLE the question value. What color is their Bugatti?",
    kind: "trapWrong", animation: "freeze", needsTarget: true, params: { confirm: true },
    emoji: "🍹", accent: "danger",
  },
  techno: {
    id: "techno", avatarId: "techno", name: "Techno", abilityName: "Sub Boom",
    tagline: "Gain +50 for every question already solved.",
    longDesc: "Instantly gain 50 points for each question the room has already completed. Sub count, meet score count.",
    kind: "subCount", animation: "zoom", immediate: true, params: { confirm: true },
    emoji: "🤖", accent: "ink",
  },
  lee: {
    id: "lee", avatarId: "lee", name: "Lee", abilityName: "Risky Lee",
    tagline: "Gamble: NORMAL ×1 or RISK ×2.",
    longDesc: "You choose during the next question: NORMAL (next correct ×1) or RISK (next correct ×2, but your next wrong costs ×−2).",
    kind: "risky", animation: "chaos", needsChoice: true, params: { risky: true },
    emoji: "🎲", accent: "secondary",
  },
  thomas: {
    id: "thomas", avatarId: "thomas", name: "Thomas Shelby", abilityName: "No F**kin' Fighting",
    tagline: "Lock a player out of buzzing for 10s.",
    longDesc: "Choose a player — they can't buzz for the first 10 seconds of the next question.",
    kind: "silence", animation: "freeze", needsTarget: true, params: { windowMs: 10000, confirm: true },
    emoji: "🎩", accent: "ink",
  },
  virat: {
    id: "virat", avatarId: "virat", name: "Virat", abilityName: "The Chase",
    tagline: "×1.5 on your next correct — while behind.",
    longDesc: "Your next correct answer is worth 1.5× IF you're still chasing the leader when you answer.",
    kind: "chaseMult", animation: "impact", params: { mult: 1.5, onlyIfChasing: true },
    emoji: "🏏", accent: "success",
  },
  walter: {
    id: "walter", avatarId: "walter", name: "Walter White", abilityName: "Say My Name",
    tagline: "Match the leader's score.",
    longDesc: "Instantly set your score equal to the current leader's. You're goddamn right.",
    kind: "copyLeader", animation: "freeze", autoTarget: true, immediate: true, params: { targetMode: "leader", confirm: true },
    emoji: "🧪", accent: "warning",
  },
  "kr$na": {
    id: "kr$na", avatarId: "kr$na", name: "Kr$na", abilityName: "Sales Round",
    tagline: "Everyone sees the answer's letter skeleton.",
    longDesc: "On the next question, the letter skeleton of the answer (first and last letter of every word) is revealed to EVERYONE in the room. Nothing gets past the whole lobby.",
    kind: "clueCommunity", animation: "glitch", params: { clueType: "skeletonAnswer" },
    emoji: "💸", accent: "secondary",
  },
};

/** All avatar ids that have an ability (every avatar in the roster). */
export const ABILITY_AVATAR_IDS: string[] = Object.keys(ABILITIES);

export const getAbilityForAvatar = (
  avatarId?: string,
): AbilityDef | undefined =>
  avatarId ? ABILITIES[avatarId] : undefined;
