/**
 * One fun "Did you know?" bite per avatar, shown on the picker dossier card.
 * Keyed by avatar id — the same id that keys ability config.
 */
export const CHARACTER_TRIVIA: Record<string, string> = {
  modi: "The world's tallest statue, the 182m Statue of Unity, was built on his watch — he remains the internet's most-memed PM by a landslide.",
  selmon: "Selmon Bhoi remade 'Bodyguard' for India and its title track became so iconic that even his entry music spawned its own remix challenge.",
  daredevil: "Daredevil is a blind lawyer who fights crime with radar-senses — the comics once described his 'powers' as 'the man without fear… and without eyes.'",
  dead: "Deadpool is played by Ryan Reynolds, who also voiced the live-action Pikachu — the only actor defeated by his own sass.",
  kratos: "Kratos began as a Greek war machine and became a Norse god-dad; the 2018 'God of War' — with just two characters — won Game of the Year.",
  thanos: "Thanos' snap erased exactly half of existence on screen — MCU fans still count the winters since the Rapture of heroes.",
  joker: "Joaquin Phoenix's turn as Arthur Fleck won the 2020 Best Actor Oscar and passed a billion at the box office — the 'clown curriculum' was born.",
  doom: "Dr. Doom is the Latverian monarch who rules with techno-priest precision — he once held the Beyonder's power for a whole story arc, then shrugged it off.",
  homelander: "Homelander (Antony Starr) is 'the world's strongest supe' whose true kryptonite is a bad tweet and an empty fridge — milk, anyone?",
  honey: "Honey Singh turbocharged desi hip-hop with 'Brown Rang' — since then, every wedding DJ runs a permanent balance deficit to Punjabi bass.",
  hritik: "'Krrish' made Hrithik India's first native superhero franchise lead — the 'Jadoo' finger step is still mandatory family-function curriculum.",
  iron: "RDJ improvised 'I am Iron Man' on the spot — one unscripted line became the moment that reshaped an entire cinematic universe.",
  john: "John Cena has granted more Make-A-Wish wishes than anyone in history — his heart is even harder to see than he is.",
  billy: "Billy Butcher's actor, Karl Urban, rode as Éomer in 'Lord of the Rings' — from Rohan's cavalry straight into supe-annihilation mode.",
  anime: "Anime Freak is the room's embassy to a multiverse — this avatar is contractually obliged to pause any match to explain three seasons of lore.",
  chims: "Chimpanzees share ~98.8% of human DNA and can learn 400+ hand signs — this avatar is basically insisting, 'I studied for this.'",
  hamza: "Hamza built a self-improvement empire on daily grindset uploads — 'Day 1' is delivered with the gravity of a team haka.",
  luffy: "'One Piece' has shipped over 500 million copies — Luffy stretched his rubber powers into the best-selling manga run in history.",
  monkey: "Monkeys have unique face-prints, just like fingerprints — science says you can't clone this avatar's vibe, only approximate it.",
  msd: "MS Dhoni finished a World Cup final with a six, then calmly explained 'thala for a reason' — he captained India to both T20 (2007) and ODI (2011) crowns.",
  perry: "Perry the Platypus doubles as Agent P — a fedora transforms a pet into a certified federal agent with his own theme jazz.",
  prabhas: "Prabhas bulked through the 'Baahubali' duology, which earned upward of ₹1,800 crore — the biggest pan-India blockbuster event of its decade.",
  professor: "The Professor scripted the Royal Mint heist down to beat 47 — his minifigure chess skills are so clean they're basically a TED talk.",
  pw: "Physics Wallah began as a free YouTube class from Alakh Pandey's living room and grew into one of India's biggest ed-tech brands.",
  raftaar: "Raftaar edits bar-for-bar across Hindi rap and Bollywood — 'Dilli Waali Baat' remains a certified textbook on double-time delivery.",
  ryder: "This avatar is powered by Prime-hydrated, messi-hyped energy — a Lamborghini that never once saw a red light.",
  samay: "Samay Raina merged stand-up, chess, and 'India's Got Latent' into one sleep-deprived brain — his 12-hour streams are endurance sports.",
  srk: "King Khan's 'Pathaan' crossed ₹1,000 crore globally — SRK still can't spread his arms wide without a stadium answering back.",
  tate: "The internet turned 'what color is your Bugatti?' into a meme institution — somewhere in the middle, a cigar just got flicked.",
  techno: "Technoblade (Toby) farmed potato supremacy in Minecraft and left the internet a single immortal sign-off: 'so long, nerds.'",
  lee: "Lee reviews edits the way coaches review replays — a legend among editors whose 'Prime' standards are non-negotiable.",
  thomas: "Tommy Shelby ran Birmingham for six seasons of 'Peaky Blinders' — his real gift is saying 'no f***in' fighting' and the room listening.",
  virat: "Virat Kohli is the fastest to 50 ODI centuries, breaking Tendulkar's long-standing record — 'the chase,' quite simply, is his religion.",
  walter: "Bryan Cranston's 'Say My Name' ranked among TV's greatest scenes — an entire memes department was born from that one phone call.",
  "kr$na": "Kr$na is one of India's fastest double-time rappers — his 'Sales Round' verses are so technical they ship with a pronunciation warning.",
};